Darkec/Models/Apartment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Darkec.Models
{
    public class Apartment : Rentable
    {

        [Required (ErrorMessage = "Apartment name is required")]
        public string Name { get; set; }

        public string Description { get; set; }

        [Required(ErrorMessage = "Apartment price is required")]
        [Range(typeof(double), "20", "100", ErrorMessage = "Value for the price should be between 20 and 100 ")]
        public double Price { get; set; }
        public User Customer { get; set; }
    }
}

Darkec/Pages/Apartments/CreateApartment.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Darkec.Models;
using Darkec.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Darkec.Pages.Apartments
{
    public class CreateApartmentModel : PageModel
    {
        [BindProperty]
        public Apartment Apartment { get; set; }

        private IObjectRepository<int, Apartment> repo;

        public CreateApartmentModel(IObjectRepository<int, Apartment> repository)
        {
            repo = repository;      
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            repo.AddObject(Apartment);
            return RedirectToPage("GetAllApartments");
        }
    }
}

Darkec/Pages/Apartments/DeleteApartment.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Darkec.Models;
using Darkec.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Darkec.Pages.Apartments
{
    public class DeleteApartmentModel : PageModel
    {
        [BindProperty]
        public Apartment Apartment { get; set; }

        private IObjectRepository<int, Apartment> repo;

        public DeleteApartmentModel(IObjectRepository<int, Apartment> repository)
        {
            repo = repository;
        }
        public IActionResult OnGet(int id)
        {
            Apartment = repo.GetObject(id);
            return Page();
        }
        public IActionResult OnPost()
        {
            repo.DeleteObject(Apartment);
            return RedirectToPage("GetAllApartments");
        }
    }
}

Darkec/Pages/Apartments/GetAllApartments.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Darkec.MockData;
using Darkec.Models;
using Darkec.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Darkec.Pages.Apartments
{
    public class GetAllApartmentsModel : PageModel
    {
        public Dictionary<int, Apartment> Catalog { get; set; }

        private IObjectRepository<int, Apartment> repo;

        public GetAllApartmentsModel(IObjectRepository<int,Apartment> repository)
        {
            repo = repository;
        }

        [BindProperty(SupportsGet = true)]
        public string FilterCriteria { get; set; }
        public Dictionary<int, Apartment> Apartments { get; private set; }

        public IActionResult OnGet()
        {
            Apartments = repo.GetAllObjects();
            if (!string.IsNullOrEmpty(FilterCriteria))
            {
                Apartments = repo.FilterObjects(FilterCriteria);
            }

            return Page();
        }
    }
}

Darkec/Pages/Apartments/GetApartment.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Darkec.Models;
using Darkec.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Darkec.Pages.Apartments
{
    public class GetApartmentModel : PageModel
    {
        [BindProperty]
        public Apartment Apartment { get; set; }

        private IObjectRepository<int, Apartment> repo;

        public GetApartmentModel(IObjectRepository<int, Apartment> repository)
        {
            repo = repository;
        }
        public IActionResult OnGet(int id)
        {
            Apartment = repo.GetObject(id);
            return Page();
        }
        public IActionResult OnPostBook(int id)
        {
            Apartment = repo.GetObject(id);
            repo.BookObject(LoginModel.CurrentUser, Apartment);
            //Order.AddApartmentToOrder(Apartment);
            return Page();
        }
        public IActionResult OnPostCancel(int id)
        {
            Apartment = repo.GetObject(id);
            repo.CancelObject(LoginModel.CurrentUser, Apartment);
            //Order.RemoveApartmentFromOrder(Apartment);
            return Page();
        }
    }
}

Darkec/Pages/Apartments/UpdateApartment.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Darkec.Models;
using Darkec.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Darkec.Pages.Apartments
{
    public class UpdateApartmentModel : PageModel
    {
        [BindProperty]
        public Apartment Apartment { get; set; }

        private IObjectRepository<int, Apartment> repo;

        public UpdateApartmentModel(IObjectRepository<int,Apartment> repository)
        {
            repo = repository;
        }
        public IActionResult OnGet(int id)
        {
            Apartment = repo.GetObject(id);
            return Page();
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            repo.UpdateObject(Apartment);
            return RedirectToPage("GetAllApartments");
        }
    }
}

Darkec/Pages/Apartments/CreateApartment.cshtml
@page
@model Darkec.Pages.Apartments.CreateApartmentModel
@{
    bool isAdmin = false;

    if (LoginModel.CurrentUser != null)
    {
        isAdmin = LoginModel.CurrentUser.IsAdmin;
    }
    ViewData["Title"] = "CreateApartment";
}

<h1>Create Apartment</h1>

<form method="post">

    <div>
        <p>Id is automatically generated</p>
    </div>
    <div class="form-group">
        <label asp-for="@Model.Apartment.Name" class="control-label">Name </label>
        <input asp-for="@Model.Apartment.Name" class="form-control" />
        <span asp-validation-for="@Model.Apartment.Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.Apartment.Description" class="control-label">Description</label>
        <input asp-for="@Model.Apartment.Description" class="form-control" />
        <span asp-validation-for="@Model.Apartment.Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.Apartment.Price" class="control-label">Price</label>
        <input asp-for="@Model.Apartment.Price" class="form-control" />
        <span asp-validation-for="@Model.Apartment.Price" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.Apartment.ImageName" class="control-label"> ImageName </label>
        <input asp-for="@Model.Apartment.ImageName" class="form-control" />
        <span asp-validation-for="@Model.Apartment.ImageName" class="text-danger"></span>
    </div>

    <div class="form-group">
        @{
            if (isAdmin == true)
            {
                <input type="submit" value="Create" class="btn btn-primary" />
            }
            else
            {
                <p>You're not an Admin, how did you get to this page?</p>
            }
        }
    </div>
</form>

Darkec/Pages/Apartments/DeleteApartment.cshtml
@page
@model Darkec.Pages.Apartments.DeleteApartmentModel
@{
    bool isAdmin = false;

    if (LoginModel.CurrentUser != null)
    {
        isAdmin = LoginModel.CurrentUser.IsAdmin;
    }
    ViewData["Title"] = "DeleteApartment";
}

<h1>Delete Apartment</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
                Name
            </th>
            <th>
                Description
            </th>
            <th>
                Price
            </th>
            <th>
                Image
            </th>
        </tr>
    </thead>
    <tbody>

        <tr>
            <td>
                @Model.Apartment.Id
            </td>
            <td>
                @Model.Apartment.Name
            </td>
            <td>
                @Model.Apartment.Description
            </td>
            <td>
                @Model.Apartment.Price
            </td>
            <td>
                <img src="~/Images/Apartments/@Model.Apartment.ImageName" width="60" height="70">
            </td>
        </tr>
    </tbody>
</table>

<form method="post">
    @{
        if (isAdmin == true)
        {
            <div class="form-group">
                <input type="submit" value="Delete" class="btn btn-danger" />
            </div>
            <div class="alert alert-danger" role="alert">
                Are you sure? This is permanent.
            </div>
        }
        else
        {
            <p>You're not an Admin, how did you get to this page?</p>
        }
    }
</form>
<br />
<div>
    <a class="btn btn-primary" asp-page="GetAllApartments">I changed my mind</a>
</div>

Darkec/Pages/Apartments/GetAllApartments.cshtml
@page
@model Darkec.Pages.Apartments.GetAllApartmentsModel
@{
    bool isAdmin = false;

    if (LoginModel.CurrentUser != null)
    {
        isAdmin = LoginModel.CurrentUser.IsAdmin;
    }
    ViewData["Title"] = "GetAllApartments";
}
<h1>Apartments</h1>

<p>
    @{
        if (isAdmin == true)
        {
            <a class="btn btn-primary" asp-page="CreateApartment">Create New Apartment</a>
        }
    }
</p>
<form>
    <div class="search_container">
        <div class="search_title">
            <input class="search_input" type="text" asp-for="FilterCriteria" placeholder="Search" /> @*submit button not implemented yet*@

        </div>
    </div>
</form>


<table class="table">
    <thead>
        <tr>
            <th>
                Image
            </th>
            <th>
                Name
            </th>
            <th>
                Description
            </th>
            <th>
                Price
            </th>

            <th>

            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model.Apartments)
        {
            <tr>
                <td>
                    <a asp-page="GetApartment" asp-route-id="@item.Key">
                        <img src="~/Images/Apartments/@item.Value.ImageName" width="180" height="150">
                    </a>
                </td>
                <td>
                    @item.Value.Name
                </td>
                <td>
                    @item.Value.Description
                </td>
                <td>
                    @item.Value.Price EUR
                </td>

                <td>
                    <p>
                        @{
                            if (isAdmin == true)
                            {
                                <a class="btn btn-primary" asp-page="UpdateApartment" asp-route-id="@item.Key">Edit</a>
                            }
                            else
                            {
                                <a class="btn btn-primary" asp-page="GetApartment" asp-route-id="@item.Key">View</a>
                            }
                        }
                    </p>
                </td>
                <td>
                    <p>
                        @{
                            if (isAdmin == true)
                            {
                                <a class="btn btn-danger" asp-page="DeleteApartment" asp-route-id="@item.Key">Delete</a>
                            }
                        }
                    </p>
                </td>
            </tr>
        }
    </tbody>

</table>

Darkec/Pages/Apartments/GetApartment.cshtml
@page
@model Darkec.Pages.Apartments.GetApartmentModel
@{
    ViewData["Title"] = "GetApartment";
}
<h1>Get Apartment</h1>

<table class="table">
    <thead>
    <tr>
        <th>
            Id
        </th>
        <th>
            Name
        </th>
        <th>
            Description
        </th>
        <th>
            Price
        </th>
        <th>
            Image
        </th>
    </tr>
    </thead>
    <tbody>

    <tr>
        <td>
            @Model.Apartment.Id
        </td>
        <td>
            @Model.Apartment.Name
        </td>
        <td>
            @Model.Apartment.Description
        </td>
        <td>
            @Model.Apartment.Price EUR
        </td>
        <td>
            <img src="~/Images/Apartments/@Model.Apartment.ImageName" width="60" height="70">
        </td>
    </tr>
    </tbody>
</table>
<img src="~/Images/Apartments/@Model.Apartment.ImageName" width="800" height="600">
<br/>
@{
    if (LoginModel.CurrentUser != null)
    {
        if (Model.Apartment.Customer == LoginModel.CurrentUser)
        {
            <form method="post" asp-page-handler="Cancel" asp-route-id="@Model.Apartment.Id">
                <div class="form-group">
                    <input type="submit" value="Cancel" class="btn btn-danger" />
                </div>
            </form>
        }
        else if (Model.Apartment.Available)
        {
            <form method="post" asp-page-handler="Book" asp-route-id="@Model.Apartment.Id">
                <div class="form-group">
                    <input type="submit" value="Book" class="btn btn-primary" />
                </div>
            </form>
        }
        else
        {
            <p class ="alert-danger">Unavailable</p>
        }
    }
    else
    {
        <p>Log in to see options</p>
    }
}
<br />
<div>
    <a class="btn btn-primary" asp-page="GetAllApartments">Back to All Apartments</a>
</div>

Darkec/Pages/Apartments/UpdateApartment.cshtml
@page
@model Darkec.Pages.Apartments.UpdateApartmentModel
@{
    bool isAdmin = false;

    if (LoginModel.CurrentUser != null)
    {
        isAdmin = LoginModel.CurrentUser.IsAdmin;
    }
    ViewData["Title"] = "Edit Apartment";
}

<h1>Edit Apartment</h1>

<form method="post">
    <div class="form-group">
        <label asp-for="@Model.Apartment.Id" class="control-label">
            Id: @Model.Apartment.Id
            <text class="alert alert-info" role="alert">
                Id cannot be changed
            </text>
        </label>
        <input hidden="hidden" asp-for="@Model.Apartment.Id" class="form-control" />
        <span asp-validation-for="@Model.Apartment.Id" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.Apartment.Name" class="control-label"></label>
        <input asp-for="@Model.Apartment.Name" class="form-control" />
        <span asp-validation-for="@Model.Apartment.Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.Apartment.Description" class="control-label"></label>
        <input asp-for="@Model.Apartment.Description" class="form-control" />
        <span asp-validation-for="@Model.Apartment.Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.Apartment.Price" class="control-label"></label>
        <input asp-for="@Model.Apartment.Price" class="form-control" />
        <span asp-validation-for="@Model.Apartment.Price" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.Apartment.ImageName" class="control-label"></label>
        <input asp-for="@Model.Apartment.ImageName" class="form-control" />
        <span asp-validation-for="@Model.Apartment.ImageName" class="text-danger"></span>
    </div>
    <div class="form-group">
        @{
            if (isAdmin == true)
            {
                <input type="submit" value="Save" class="btn btn-primary" />
            }
            else
            {
                <p>You're not an Admin, how did you get to this page?</p>
            }
        }
    </div>
</form>